spring:
  application:
    name: ads-service

server:
  port: "${DEFAULT_SERVICE_PORT:9510}"

eureka:
  client:
    service-url:
      defaultZone: "${DEFAULT_EUREKA_SERVER:http://localhost:9500/eureka}"
  instance:
    prefer-ip-address: true