spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: api-services
          uri: lb://url-service
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}
server:
  port: "${DEFAULT_SERVICE_PORT:9540}"

eureka:
  client:
    service-url:
      defaultZone: "${DEFAULT_EUREKA_SERVER:http://localhost:9500/eureka}"
  instance:
    prefer-ip-address: true