spring:
  application:
    name: url-service

server:
  port: "${DEFAULT_SERVICE_PORT:9520}"

eureka:
  client:
    service-url:
      defaultZone: "${DEFAULT_EUREKA_SERVER:http://localhost:9500/eureka}"
  instance:
    prefer-ip-address: true

#  servlet:
#    context-path=/url